# Generated by Django 4.1.4 on 2022-12-31 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollsApp2', '0002_alter_question_options_question_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 31, 8, 29, 50, 995737, tzinfo=datetime.timezone.utc)),
        ),
    ]
